### ISSUE TITLE
Update Checklist CMS

### ISSUE THREAD

**Issue by lisaratner** [codeforamerica/bizport#257]
- [x] h1 should be smaller ("Learn")
- [x] Remove checklist items with "-", re-add with "+"
- [ ] Restyle checklist box area
- [x] Change "Save" CTA when logged in/out

**Comment by lisaratner** [comment]
![new user](https://cloud.githubusercontent.com/assets/16671878/17452165/a5bf884e-5b21-11e6-9c91-1f1a9269d1cb.jpg)
![logged in user](https://cloud.githubusercontent.com/assets/16671878/17452164/a5a4bcda-5b21-11e6-9b31-7465ef4117b0.jpg)

**Comment by rossettistone** [comment]
This remains the first priority for the Profile project, but we need to settle the question of Login integration with Rhythm before moving forward on that project. Moving this to the backlog temporarily.

**Comment by rossettistone** [comment]
@lisaratner Can you try uploading the photo/screenshot above again? Think it failed due to slow wifi or something.

**Comment by lisaratner** [comment]
![page - new user](https://cloud.githubusercontent.com/assets/16671878/17829048/acbea2da-6655-11e6-9237-82f520b25762.jpg)

**Comment by lisaratner** [comment]
I need to upload the restyled checklist page.

**Comment by lisaratner** [comment]
SMEs will edit these on the content doc with @rossettistone thrusday

**Comment by lisaratner** [comment]
@heidiwiersma can you close this issue when you are done updating the checklist
